### ISSUE TITLE
Force SSL error warning after activation

### ISSUE THREAD

**Issue by bibekpthk** [khalti/khalti-woocommerce#10]
When the site is already running over SSL, wocommerce does not provide force ssl at checkout option (because entire site is already over SSL). Khalti plugin does not check that and keeps on showing following message:

`Khalti is enabled, but the Force SSL option is disabled; your checkout may not be secure! Please enable SSL and ensure your server has a valid SSL certificate - Gateway Name will only work in sandbox mode.`

**Comment by manibibek** [comment]
Hi @bibekpthk 

The issue has been addressed now. 

Thanks
