### ISSUE TITLE
Pay with Khalti not appearing in checkout options

### ISSUE THREAD

**Issue by sdangol** [khalti/khalti-woocommerce#9]
## Summary

Pay with Khalti option is not seen during the checkout even though the test keys and secret keys are added

## Expected Behavior
Payment option should be available during checkout

## Current Behavior
Payment option is not showing up

## Steps to Reproduce
- Install the plguin and activate it
- Activate Khalti option in woocommerce payment settings
- Check enable khalti checkbox and sandbox checkbox
- Add test secret and public keys
- Save the changes and checkout an item

## System Status
[system_status.txt](https://github.com/khalti/khalti-woocommerce/files/4301547/system_status.txt)

**Comment by surajvdya** [comment]
I am also having same problem when adding the plugin

**Comment by manibibek** [comment]
This plugin only supports NPR currently. Is your selected currency NPR while checkout?

**Comment by surajvdya** [comment]
@manibibek  Thankyou very much!
 it worked :)
